## **Simple Printing**

In [ ]:
print("Hello World!!")

Hello World!!


## **Concept of Variables**

In [ ]:
name="node 1"

print(name)

node 1


## **Concept of Data Types**

In [ ]:
name = "node"
temperature=30
humidity=70.5
is_active=True

print(name)
print(temperature)
print(humidity)
print(is_active)

print(type(name))
print(type(temperature))
print(type(humidity))
print(type(is_active))

node
30
70.5
True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


## **Input and Output**

In [ ]:
sensor = input("Enter name of the sensor: ")

print(sensor)

temperature = int(input("Enter temperature: "))

print(temperature)

humidity = float(input("Enter humidity: "))

print(humidity)

is_active = bool(input("Enter True or False: "))  # always True as any non empty string is treated as True

print(is_active)

is_active = input("Enter True or False: ") == "True"

print(is_active)

Enter name of the sensor: node 1
node 1
Enter temperature: 35
35
Enter humidity: 45.5
45.5
Enter True or False: False
True
Enter True or False: False
False


## **Conditional and Loop**

## If - Else

In [ ]:
current_temperature = int(input("Enter current temperature: "))

if current_temperature > 35:
    print("Alert!!!")
else:
    print("Temperature is normal")

Enter current temperature: 20
Temperature is normal


## For Loop

In [ ]:
for count in range(10):
    print(count)

0
1
2
3
4
5
6
7
8
9


## While Loop

In [ ]:
count=1

while count<=10:
  print(count)
  count=count+1

1
2
3
4
5
6
7
8
9
10


## **Functions**

In [ ]:
def check_temperature(temperature):
  if temperature > 35:
    print("Alert!!!")
  else:
    print("Temperature is normal")


check_temperature(25)
check_temperature(55)

Temperature is normal
Alert!!!


## **Data Structure**

# List

# Creating List

In [ ]:
list_a = [1,2,3,4,5]
list_b = ["abc","xyz","pqr"]
list_c = [1,"abc",2.5,True]

print(list_a)
print(list_b)
print(list_c)

list_d = list(range(10))  #iterables inside list constructor
list_e = list("abc")

print(list_d)
print(list_e)

[1, 2, 3, 4, 5]
['abc', 'xyz', 'pqr']
[1, 'abc', 2.5, True]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'b', 'c']


# Accessing List Elements

In [ ]:
a = [10,20,30,40,50]

print(a[1:5:2])

print(a[-1])

[20, 40]
50


# Inserting Elements into List

In [ ]:
a.append(60)

print(a)

a.extend([70,80,90])

print(a)

a.insert(0,5)

print(a)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 70, 80, 90]
[5, 10, 20, 30, 40, 50, 60, 70, 80, 90]


# Clearing Elements from List

In [ ]:
a.clear()

print(a)

[]


# Updating Element into List

In [ ]:
a = [10,20,30,40,50]

a[2]=35

print(a)

[10, 20, 35, 40, 50]


# Removing Elements from List

In [ ]:
a = [10,20,30,40,50]

a.remove(40)  #give value to delete

print(a)

a.pop(1)  #give index to delete

print(a)

a.pop()

print(a)

del a[0]

print(a)

[10, 20, 30, 50]
[10, 30, 50]
[10, 30]
[30]


# Iterating over List

In [ ]:
a = [10,20,30,40,50]

for element in a:
  print(element)

10
20
30
40
50


# Joining Lists

In [ ]:
l1=[1,2,3]
l2=[4,5,6]

l3=l1+l2

print(l3)

[1, 2, 3, 4, 5, 6]


# Tuple

# Creating Tuple

In [ ]:
t1 = (1,2,3,4,5)

t2 = ('a','b','c')

t3 = (1,'a',2.5,True)

print(t1)
print(t2)
print(t3)

t4 = tuple([1,2,3,4,5])

t5 = tuple("abc")

print(t4)
print(t5)

(1, 2, 3, 4, 5)
('a', 'b', 'c')
(1, 'a', 2.5, True)
(1, 2, 3, 4, 5)
('a', 'b', 'c')


# Accessing Tuple Elements

In [ ]:
t1 = (10,20,30,40,50)

print(t1[1:5:2])

print(t1[-1])

(20, 40)
50


# Unpacking Tuple

In [ ]:
t1 = (10,20,30)

a,b,c = t1

print(a)
print(b)
print(c)

10
20
30


# Looping and Joining Tuples are same as for List

# Set

Creating Set

In [ ]:
s = {1,2,3,4,5}

print(s)

s2 = set([1,2,3,4,5])

print(s2)

s3 = set("abc")

print(s3)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{'a', 'b', 'c'}


Looping through Set

In [ ]:
s = {1,2,3,4,5}

for element in s:
  print(element)

1
2
3
4
5


Adding element in Set

In [ ]:
s = {1,2,3,4,5}

s.add(6)

print(s)

{1, 2, 3, 4, 5, 6}


Adding multiple elemnts from another set to a set

In [ ]:
s1 = {1,2,3}

s2 = {4,5,6}

s1.update(s2)

print(s1)

{1, 2, 3, 4, 5, 6}


Removing element from Set

In [ ]:
s = {1,2,3,4,5}

s.remove(4)

print(s)

s.discard(5)

print(s)

s.pop()

print(s)

{1, 2, 3, 5}
{1, 2, 3}
{2, 3}


# Dictionary

Creating dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

print(d)

d2 = dict([("node1",10),("node2",20),("node3",30)])

print(d2)


{'node1': 10, 'node2': 20, 'node3': 30}
{'node1': 10, 'node2': 20, 'node3': 30}


Accessing Dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

print(d["node1"])
print(d.get("node2"))
print(d.keys())
print(d.values())
print(d.items())

10
20
dict_keys(['node1', 'node2', 'node3'])
dict_values([10, 20, 30])
dict_items([('node1', 10), ('node2', 20), ('node3', 30)])


Changing dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

d["node1"]=15

print(d)

d.update({"node2":25})

print(d)

{'node1': 15, 'node2': 20, 'node3': 30}
{'node1': 15, 'node2': 25, 'node3': 30}


Adding Items in dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

d.update({"node4":40})

print(d)

{'node1': 10, 'node2': 20, 'node3': 30, 'node4': 40}


Deleting Items from dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

d.pop("node1")

print(d)

d.popitem()

print(d)

del d["node2"]

print(d)

{'node2': 20, 'node3': 30}
{'node2': 20}
{}


Looping through dictionary

In [ ]:
d = {"node1":10,"node2":20,"node3":30}

for key in d:
  print(key)
  print(d[key])

for key,value in d.items():
  print(key)
  print(value)

for key in d.keys():
  print(key)

for value in d.values():
  print(value)

node1
10
node2
20
node3
30
node1
10
node2
20
node3
30
node1
node2
node3
10
20
30


# **Numpy**

## Creating 1D array

In [ ]:
import numpy as np

temperatures = np.array([10,20,30,40,50])

print(temperatures)

print(type(temperatures))

print(temperatures.shape)

print(temperatures.dtype)

print(temperatures.ndim)

print(temperatures.size)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)
int64
1
5


## Creating a 2D array

In [ ]:
temp_and_humidity = np.array([[10,20,30],[40,50,60]])

print(temp_and_humidity)

print(type(temp_and_humidity))

print(temp_and_humidity.shape)

print(temp_and_humidity.dtype)

print(temp_and_humidity.ndim)

print(temp_and_humidity.size)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
(2, 3)
int64
2
6


## Accessing elements from 1D array

In [ ]:
temperatures = np.array([10,20,30,40,50])

print(temperatures[0])
print(temperatures[1])

print(temperatures[-1])
print(temperatures[-2])

10
20
50
40


## Accessing elements from 2D array

In [ ]:
temp_and_humidity = np.array([[10,20,30],[40,50,60]])

print(temp_and_humidity[0,2])

print(temp_and_humidity[1,2])

print(temp_and_humidity[1,-1])

30
60
60


## Slicing 1D array

In [ ]:
temperatures = np.array([10,20,30,40,50])

print(temperatures[1:4])

print(temperatures[1:4:2])

print(temperatures[1:])

print(temperatures[:3])

print(temperatures[-3:-1])

print(temperatures[-3:-1:2])

print(temperatures[::2])

[20 30 40]
[20 40]
[20 30 40 50]
[10 20 30]
[30 40]
[30]
[10 30 50]


## Slicing 2D array

In [ ]:
temp_and_humidity = np.array([[10,20,30],[40,50,60]])

print(temp_and_humidity[0,1:3])

print(temp_and_humidity[1,1:])

print(temp_and_humidity[0:2,2])

print(temp_and_humidity[:,1])

print(temp_and_humidity[0:2,1:3])

print(temp_and_humidity[:,::2])

print(temp_and_humidity[::2,:])

[20 30]
[50 60]
[30 60]
[20 50]
[[20 30]
 [50 60]]
[[10 30]
 [40 60]]
[[10 20 30]]


## Reshaping Arrays

In [9]:
temperatures = np.array([10,20,30,40,50,60])

print(temperatures.reshape(2,3))

print(temperatures.reshape(3,2))

[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


## Arithmetic functions on Numpy arrays

In [11]:
temperatures_1 = np.array([10,20,30,40,50])

temperatures_2 = np.array([5,10,15,20,25])

print(np.add(temperatures_1,temperatures_2))

print(np.subtract(temperatures_1,temperatures_2))

print(np.multiply(temperatures_1,temperatures_2))

print(np.divide(temperatures_1,temperatures_2))

print(np.mod(temperatures_1,temperatures_2))

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[0 0 0 0 0]


## Summation over different axis in Numpy

In [12]:
temperatures_1 = np.array([10,20,30,40,50])

temperatures_2 = np.array([5,10,15,20,25])

print(np.sum([temperatures_1,temperatures_2]))

print(np.sum([temperatures_1,temperatures_2],axis=0))

print(np.sum([temperatures_1,temperatures_2],axis=1))

225
[15 30 45 60 75]
[150  75]


## Concatenation of Two 1D arrays

In [13]:
temperatures_1 = np.array([10,20,30,40,50])

temperatures_2 = np.array([5,10,15,20,25])

print(np.concatenate((temperatures_1,temperatures_2)))  # same shape

print(np.stack((temperatures_1,temperatures_2),axis=1)) # have one more dimension than input dimension

print(np.hstack((temperatures_1,temperatures_2)))

print(np.vstack((temperatures_1,temperatures_2)))

print(np.dstack((temperatures_1,temperatures_2)))

[10 20 30 40 50  5 10 15 20 25]
[[10  5]
 [20 10]
 [30 15]
 [40 20]
 [50 25]]
[10 20 30 40 50  5 10 15 20 25]
[[10 20 30 40 50]
 [ 5 10 15 20 25]]
[[[10  5]
  [20 10]
  [30 15]
  [40 20]
  [50 25]]]


## Concatenation of Two 2D arrays

In [15]:
temp_and_humidity_1 = np.array([[10,20,30],[40,50,60]])

temp_and_humidity_2 = np.array([[5,10,15],[20,25,30]])

print(np.concatenate((temp_and_humidity_1,temp_and_humidity_2),axis=0))

print(np.concatenate((temp_and_humidity_1,temp_and_humidity_2),axis=1))

print(np.stack((temp_and_humidity_1,temp_and_humidity_2),axis=1))

print(np.hstack((temp_and_humidity_1,temp_and_humidity_2)))

print(np.vstack((temp_and_humidity_1,temp_and_humidity_2)))

print(np.dstack((temp_and_humidity_1,temp_and_humidity_2)))

[[10 20 30]
 [40 50 60]
 [ 5 10 15]
 [20 25 30]]
[[10 20 30  5 10 15]
 [40 50 60 20 25 30]]
[[[10 20 30]
  [ 5 10 15]]

 [[40 50 60]
  [20 25 30]]]
[[10 20 30  5 10 15]
 [40 50 60 20 25 30]]
[[10 20 30]
 [40 50 60]
 [ 5 10 15]
 [20 25 30]]
[[[10  5]
  [20 10]
  [30 15]]

 [[40 20]
  [50 25]
  [60 30]]]


# **Pandas**

## Creating Dataframe

In [2]:
import pandas as pd

details = {
    "node_1":[10,20,30],
    "node_2":[40,50,60],
    "node_3":[70,80,90]
}

df = pd.DataFrame(details)

print(df)

print(type(df))

print(df.shape)

print(df.size)

print(df.ndim)

print(df.columns)

print(df.index)

print(df.dtypes)

print(df.info())

print(df.head(2))

print(df.tail(2))

print(df.describe())

print(df.T)

   node_1  node_2  node_3
0      10      40      70
1      20      50      80
2      30      60      90
<class 'pandas.core.frame.DataFrame'>
(3, 3)
9
2
Index(['node_1', 'node_2', 'node_3'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
node_1    int64
node_2    int64
node_3    int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   node_1  3 non-null      int64
 1   node_2  3 non-null      int64
 2   node_3  3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None
   node_1  node_2  node_3
0      10      40      70
1      20      50      80
   node_1  node_2  node_3
1      20      50      80
2      30      60      90
       node_1  node_2  node_3
count     3.0     3.0     3.0
mean     20.0    50.0    80.0
std      10.0    10.0    10.0
min      10.0    40.0    70.0
25%      15.0    45.0    75.0
50%      20.0    50.0    80.0
75%   

## Setting Index Name

In [28]:
df = pd.DataFrame(details,index=["temp","humidity","pressure"])

print(df)

print(df.index)

          node_1  node_2  node_3
temp          10      40      70
humidity      20      50      80
pressure      30      60      90
Index(['temp', 'humidity', 'pressure'], dtype='object')


## Locating row in dataframe

In [30]:
print(df.loc["temp"])

print(df.loc["temp","node_1"])

print(df.loc[["temp","pressure"]])

print(df.loc[["temp","pressure"],["node_1","node_2"]])


node_1    10
node_2    40
node_3    70
Name: temp, dtype: int64
10
          node_1  node_2  node_3
temp          10      40      70
pressure      30      60      90
          node_1  node_2
temp          10      40
pressure      30      60


## Converting file to dataframe

In [37]:
df = pd.read_csv("sensor_data_with_errors.csv")

print(df)

#print(df.head())

   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          30       60        72          95.0
1      S002  2026-04-01          31       65        80          90.0
2      S003  2026-04-01         NaN       58        75          88.0
3      S004  2026-04-01          29      NaN        70          85.0
4      S005  2026-04-01          35       72       NaN          80.0
5      S006  2026-04-01          33       68        78           NaN
6      S002  2026-04-01          31       65        80          90.0
7      S007  2026/04/01          32       66        74          87.0
8      S008  01-04-2026      Thirty       70        76          89.0
9      S009  2026-04-01          28      105        65          92.0
10     S010  2026-04-01          -5       55        68          91.0
11     S011  2026-04-01          34    sixty        77          88.0
12     S012  2026-04-01          36       75       abc          86.0
13     S013  2026-04-01          3

## Deleting rows having empty values

In [39]:
cleaned_df = df.dropna()

print(cleaned_df)
#print(cleaned_df.head())

df.dropna(inplace=True) # delete from original dataframe

print(df)
#print(df.head())

   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          30       60        72          95.0
1      S002  2026-04-01          31       65        80          90.0
6      S002  2026-04-01          31       65        80          90.0
7      S007  2026/04/01          32       66        74          87.0
8      S008  01-04-2026      Thirty       70        76          89.0
9      S009  2026-04-01          28      105        65          92.0
10     S010  2026-04-01          -5       55        68          91.0
11     S011  2026-04-01          34    sixty        77          88.0
12     S012  2026-04-01          36       75       abc          86.0
13     S013  2026-04-01          31       64        73         150.0
14     S014  2026-04-01          30       61        71         -10.0
15     S015  2026-13-01          29       60        70          90.0
   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          3

## Filling Missing values

In [41]:
df = pd.read_csv("sensor_data_with_errors.csv")

df.fillna(100,inplace=True)

print(df)

   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          30       60        72          95.0
1      S002  2026-04-01          31       65        80          90.0
2      S003  2026-04-01         100       58        75          88.0
3      S004  2026-04-01          29      100        70          85.0
4      S005  2026-04-01          35       72       100          80.0
5      S006  2026-04-01          33       68        78         100.0
6      S002  2026-04-01          31       65        80          90.0
7      S007  2026/04/01          32       66        74          87.0
8      S008  01-04-2026      Thirty       70        76          89.0
9      S009  2026-04-01          28      105        65          92.0
10     S010  2026-04-01          -5       55        68          91.0
11     S011  2026-04-01          34    sixty        77          88.0
12     S012  2026-04-01          36       75       abc          86.0
13     S013  2026-04-01          3

## Filling missing values with mean, median and mode

In [44]:
df = pd.read_csv("sensor_data_with_errors.csv")

df["BatteryLevel"].fillna(df["BatteryLevel"].mean(),inplace=True)

print(df)

   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          30       60        72     95.000000
1      S002  2026-04-01          31       65        80     90.000000
2      S003  2026-04-01         NaN       58        75     88.000000
3      S004  2026-04-01          29      NaN        70     85.000000
4      S005  2026-04-01          35       72       NaN     80.000000
5      S006  2026-04-01          33       68        78     86.066667
6      S002  2026-04-01          31       65        80     90.000000
7      S007  2026/04/01          32       66        74     87.000000
8      S008  01-04-2026      Thirty       70        76     89.000000
9      S009  2026-04-01          28      105        65     92.000000
10     S010  2026-04-01          -5       55        68     91.000000
11     S011  2026-04-01          34    sixty        77     88.000000
12     S012  2026-04-01          36       75       abc     86.000000
13     S013  2026-04-01          3

/tmp/ipykernel_1487/4101152225.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BatteryLevel"].fillna(df["BatteryLevel"].mean(),inplace=True)


## Delete duplicate entries

In [3]:
df = pd.read_csv("sensor_data_with_errors.csv")

print(df.duplicated())

df.drop_duplicates(inplace=True)

print(df)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool
   SensorID        Date Temperature Humidity HeartRate  BatteryLevel
0      S001  2026-04-01          30       60        72          95.0
1      S002  2026-04-01          31       65        80          90.0
2      S003  2026-04-01         NaN       58        75          88.0
3      S004  2026-04-01          29      NaN        70          85.0
4      S005  2026-04-01          35       72       NaN          80.0
5      S006  2026-04-01          33       68        78           NaN
7      S007  2026/04/01          32       66        74          87.0
8      S008  01-04-2026      Thirty       70        76          89.0
9      S009  2026-04-01          28      105        65          92.0
10     S010  2026-04-01          -5       55        68          91.0
11     S011  2026-04-01          34  